Integration Openapi documentation
cuenca-mx/fast-agave pull request #103
Opened 2022-05-19 15:57 UTC by rogelioLpz

Update fastapi routes to add schemas and samples from OpenAPi docs

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/10482303/171277643-bf39bc8f-a8ec-43fb-8ab5-9326c7ae3b21.png">

<img width="238" alt="image" src="https://user-images.githubusercontent.com/10482303/171277440-4fdad057-1cac-45a5-9216-519effd77653.png">

2022-05-25 15:45 UTC, pachCode approved these changes

2022-06-01 00:41 UTC, felipaoo requested changes

2022-06-01 00:41 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +    @staticmethod
no es necesario que este sea un método estatico, puede ser una función fuera de la clase

2022-06-01 00:41 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +    def _openapi(code: int, description, samples: List[Dict]):
agregar tipo de retorno

2022-06-01 00:41 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +                items: Optional[List[response_model or Any]] = Field(
cuando no hay elementos en `items` la lista es vacía, por lo que debe cambiar el type annotation. Deberia ser `List[response_model] = []`

2022-06-01 00:41 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +                next_page_uri: Optional[str] = Field(
creo que vale la pena ser consistentes con la forma de poner `description` que se usa en cuenca-python

2022-06-01 00:41 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +                items: Optional[List[response_model or Any]] = Field(
en qué caso es necesario en `Any`?

2022-06-01 00:41 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +                f'Make queries in resource {cls.__name__} and filter the result using query parameters.  \n'
no convedrá usar f-strings multiline?
```python
f"""
foo {1+1}
bar
"""
```

así ya no tienes que poner los `\n`

2022-06-01 00:41 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +                    responses={**error_404},
según veo `error_404` ya es un diccionario y no es necesario hacer `{**error_404}`

2022-06-01 18:14 UTC, rogelioLpz commented on fast_agave/blueprints/rest_api.py
> +                f'Make queries in resource {cls.__name__} and filter the result using query parameters.  \n'
Si lo habia considerado pero como interpreta el string como markdown lo pone en formato de código, no como texto
<img width="807" alt="image" src="https://user-images.githubusercontent.com/10482303/171474008-add96f6c-4102-4bc5-89fe-0d78e4f8303c.png">

2022-06-01 18:23 UTC, rogelioLpz commented on fast_agave/blueprints/rest_api.py
> +                items: Optional[List[response_model or Any]] = Field(
FastAPI utiliza el response_model definido en la [ruta](https://github.com/cuenca-mx/fast-agave/blob/openapi/fast_agave/blueprints/rest_api.py#L314) para validar la respuesta antes de contestar al cliente.
Eso esta bien porque el mismo server valida el cliente pero si  no esta definido el atributo`response_model` en la clase da error.  
Al poner el `Any` hace que si no esta defindo permita devolver cualquier cosa

2022-06-01 21:58 UTC, merged