agave
cuenca-mx/fast-agave pull request #11
Opened 2021-04-22 01:27 UTC by felipaoo

implementación de blueprints para definir  casi la misma estructura resources que agave usando los modelos y clases de fastapi
closes #1 
closes #2

2021-04-24 13:36 UTC, rogelioLpz commented on fast_agave/blueprints/rest_api.py
> +        """Decorator to transform a class in Chalice REST endpoints
Cambiar comments, ya no es Chalice

2021-04-24 13:49 UTC, rogelioLpz commented on examples/resources/accounts.py
> +            raise NotFoundError
Que tal si pones esto en el Blueprint, es algo que siempre se va a hacer para un delete

2021-04-24 14:02 UTC, rogelioLpz commented on fast_agave/blueprints/rest_api.py
> +            async def query(request: Request):
Para el query no se debería validar que existan los atributos `query_validator` y `get_query_filter`?
Si algún resource no necesite queries y no los define se estaría creando de todos modos no ?

2021-04-24 14:11 UTC, rogelioLpz commented on fast_agave/blueprints/rest_api.py
> +                    query.limit = max(0, query.limit - limit)  # type: ignore
Porque el  ` # type: ignore` ?

2021-04-24 14:29 UTC, rogelioLpz commented on requirements.txt
> +agave[mongo]==0.1.7.dev0
Esta dependencia se me hace algo extraña. 
Se supone que esta librería hace lo mismo que agave y no debería depender de ella.
Veo que se usan funciones de mongo y creo que lo mejor es sacar ese código de agave  y ponerlo en otro paquete (similar a [mongo-extras](https://pypi.org/project/mongoengine-extras)) así solo tendrías la dependencia de mongo pero no de agave

2021-04-24 14:56 UTC, rogelioLpz requested changes
Dejo comentarios

2021-04-26 18:42 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +            async def query(request: Request):
>Para el query no se debería validar que existan los atributos query_validator y get_query_filter?

cuál sería el propósito de validar que existan? retornar un 400, 404, 500?

>Si algún resource no necesite queries y no los define se estaría creando de todos modos no ?
si,  en el diseño actual se crea un query implicitamente

2021-04-26 18:56 UTC, felipaoo commented on requirements.txt
> +agave[mongo]==0.1.7.dev0
La idea es reutilizar funciones o métodos definidos en agave. En el pull de agave se hacen dependencias opcionales a chalice y mongo. 

>  sacar ese código de agave y ponerlo en otro paquete
 
Lo vimos como una buena opción pero vimos que haría crear un nivel dependencia extra a los proyectos que usen agave. Este es el pull reacionado https://github.com/cuenca-mx/agave/pull/77

2021-04-26 19:11 UTC, rogelioLpz commented on fast_agave/blueprints/rest_api.py
> +            async def query(request: Request):
Así como esta siempre se esta creando el endpoint `GET /resource?params` para todos los resources.
Pero si el resource no tiene los atributos  `query_validator` y `get_query_filter` no se debería que crear ese enpoint GET. 
Esto significaría que el resource no va a ser `Queryable`. Por ejemplo el resource de ARPC

2021-04-27 00:38 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +            async def query(request: Request):
vaa, creo lo mas adecuado es retornar un 422

2021-05-03 18:41 UTC, rogelioLpz commented on requirements.txt
> +agave[mongo]==0.1.7.dev0
https://pypi.org/project/mongoengine-plus/

2021-05-03 22:36 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +            async def query(request: Request):
veo que es más  adecuado https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

2021-05-03 23:14 UTC, rogelioLpz commented on fast_agave/blueprints/rest_api.py
> +                    return Response(content=dict(), status_code=405)
Que opinas de ponerlo así?
``` python
from fastapi import HTTPException
..

if not hasattr(cls, 'query_validator'):
   raise HTTPException(405)
```

2021-05-03 23:30 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +                    return Response(content=dict(), status_code=405)
se ve bien, lo cambio

2021-05-04 00:32 UTC, rogelioLpz commented on fast_agave/filters.py
> +def generic_query(query):
TypeHint

`def generic_query(query: Type[BaseModel]) -> Q:`

2021-05-04 00:37 UTC, rogelioLpz commented on fast_agave/models/async_base_model.py
> +        return await create_awaitable(self.save, *args, **kwargs)
Ves conveniente mover esto a `mongoengine-plus` ? 
O es mejor conservarlo aquí hasta que se haga un proyecto `mongoengine-async`?

2021-05-04 00:49 UTC, rogelioLpz commented on requirements.txt
> +cuenca-validations==0.9.3
Estarías removiendo de una vez esta dependencia?  solo esta en 2 lados
[aquí](https://github.com/cuenca-mx/fast-agave/blob/agave/fast_agave/blueprints/rest_api.py#L193 ) se puede remplazar QueryParams por Type[BaseModel]
y [aquí](https://github.com/cuenca-mx/fast-agave/blob/agave/examples/validators.py#L3) es un ejemplo por lo se podría colocar la clase directamente

2021-05-04 16:59 UTC, felipaoo commented on fast_agave/models/async_base_model.py
> +        return await create_awaitable(self.save, *args, **kwargs)
yo creo que conviene moverlo, así ustedes pueden usarlo en sus proyectos hasta que encontremos una buena biblioteca como la de mongoengine asyncio

2021-05-04 21:06 UTC, felipaoo commented on fast_agave/filters.py
> +def generic_query(query):
no puede ser `Type[BaseModel]` de hecho el tipo debe ser `QueryParam` del paquete de cuenca-validations

2021-05-04 21:07 UTC, felipaoo commented on fast_agave/models/async_base_model.py
> +        return await create_awaitable(self.save, *args, **kwargs)
integrado en https://github.com/cuenca-mx/mongoengine-plus/pull/5

2021-05-04 21:08 UTC, felipaoo commented on requirements.txt
> +cuenca-validations==0.9.3
me parece que no podré quitarlo, pues en este se necesita para typehint https://github.com/cuenca-mx/fast-agave/pull/11#discussion_r625447693

2021-05-04 21:10 UTC, felipaoo commented on requirements.txt
> +cuenca-validations==0.9.3
no podría ser de tipo `Type[BaseModel]` aunque `QueryParam` es un `BaseModel` mypi detecta que no contiene propiedades como `created_before`

2021-05-04 21:44 UTC, rogelioLpz approved these changes

2021-05-12 21:43 UTC, merged