Exceptions
cuenca-mx/fast-agave pull request #21
Opened 2021-06-03 20:59 UTC by ricardo8990

- Agrega excepciones similares a las que teníamos con Chalice para mantener consistencia
- Cuando un parámetro de recurso llega como `me` lo sustituye por el `user_id`
- No agrega el filtro `user_id` cuando no existe en el modelo
- Se modifica `copy_attributes` para no sustituir atributos privados

2021-06-03 22:57 UTC, felipaoo requested changes

2021-06-03 22:57 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +        resource_id = (
test?

2021-06-03 22:57 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +                async def delete(id: str, request: Request):
porque sería necesario acceder al request desde estos métodos?

2021-06-04 00:08 UTC, ricardo8990 commented on fast_agave/blueprints/rest_api.py
> +        resource_id = (
Porqué test?

2021-06-04 00:10 UTC, ricardo8990 commented on fast_agave/blueprints/rest_api.py
> +                async def delete(id: str, request: Request):
Hay situaciones donde el método `delete` tiene un tiempo de expiración en el body como [aquí](https://github.com/cuenca-mx/cuenca-python/blob/4e0bbbb56b42a02b44d40764bb68537cc768bc4c/cuenca/resources/api_keys.py#L47), este solo puede obtenerse del objeto `Request`

2021-07-31 00:32 UTC, felipaoo approved these changes

2021-07-31 00:33 UTC, merged