Platforms
cuenca-mx/fast-agave pull request #66
Opened 2022-01-11 17:37 UTC by felipaoo

closes #65

2022-02-15 18:23 UTC, rogelioLpz commented on examples/resources/accounts.py
> +            platform_id=TEST_DEFAULT_PLATFORM_ID,
Para que quede mejor el ejemplo no sería así?
`platform_id= app. current_platform_id `

2022-02-15 18:24 UTC, rogelioLpz commented on fast_agave/version.py
> +__version__ = '0.3.0.dev5'
version

2022-02-15 19:01 UTC, rogelioLpz reviewed
Solo falta subir coverage a 100

2022-02-16 19:40 UTC, pachCode commented on fast_agave/blueprints/rest_api.py
> +        if self.platform_id_filter_required() and hasattr(
Con esto no tronarían los endpoints de oaxaca  no? @felipaoo

2022-02-16 19:41 UTC, pachCode requested changes
Si, solo algunas preguntas, la versión y el coverage

2022-02-21 19:48 UTC, felipaoo commented on fast_agave/blueprints/rest_api.py
> +        if self.platform_id_filter_required() and hasattr(
ya no, se aplica la misma lógica para los `query`. Ya no será necesarias los filtros específicos

2022-02-21 19:51 UTC, felipaoo commented on examples/middlewares/authed.py
> +    def required_platform_id(self) -> bool:
cuando lo hago una propiedad no se comporta como espero. Hace cosas extrañas cuando hago mock sobre esas propiedades en tests

2022-02-23 17:33 UTC, pachCode approved these changes

2022-02-23 17:34 UTC, pachCode approved these changes

2022-02-23 17:37 UTC, merged