SQS Retry logic ⚡
cuenca-mx/fast-agave pull request #81
Opened 2022-02-23 23:54 UTC by andreshndz

This PR gives an approach to retry tasks in SQS
It will help Hermes retrying webhooks

2022-02-24 17:08 UTC, agarrido19 commented on fast_agave/tasks/sqs_tasks.py
> +        print('pase')
quitar print :v

2022-02-25 00:09 UTC, felipaoo requested changes
Falta agregar un ejemplo en `examples.tasks.example_tasks` de cómo debe usarse este feature

2022-02-25 00:09 UTC, felipaoo commented on fast_agave/tasks/sqs_tasks.py
> +    except RetryTask:
El único inconveniente que le veo a esta lógica es que podría ciclarse por siempre.  Conviene agregar una lógica de máximo número de reintentos.

Esto lo puedes lograr con  el metadata que viene al recibir el mensaje: `ApproximateReceiveCount `. Aunque usamos `aiobotocore` como cliente copio de la documentación de boto3 (usan la misma interfaz en cuanto a llamadas) https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.receive_message

2022-02-25 00:09 UTC, felipaoo commented on tests/tasks/test_sqs_tasks.py
> +    async_mock_function = AsyncMock(side_effect=RetryTask)
Este test no valida el escenario completo que queremos probar:
1. El task debe volver a ejecutarse cuando se lanza `TaskRetry`
2. El mensaje debe eliminarse del queue cuando el task termina exitosamente

2022-03-04 23:25 UTC, felipaoo requested changes

2022-03-04 23:25 UTC, felipaoo commented on fast_agave/tasks/sqs_tasks.py
> +        if last_retry:
se ve bien! 

solo veo como duplicado la llamada a `delete_message`. Esto creo podría resolverse como:

```python
async def run_task(..., last_retry):
   try:
      await coro:
   except RetryTask:
      return
   finally:
      if last_retry:
         sqs.delete_message(...)
   
```

2022-03-04 23:25 UTC, felipaoo commented on tests/tasks/test_sqs_tasks.py
> +
parece que el test de arriba prueba el mismo caso que este. Conviene dejar este

2022-03-04 23:25 UTC, felipaoo commented on tests/tasks/test_sqs_tasks.py
> +    assert 'Messages' not in resp
agregar un test donde en todos los reintentos falle con una excepción inesperada, validar que todos los reintentos y al final debe eliminar el mensaje

2022-03-04 23:25 UTC, felipaoo commented on fast_agave/tasks/sqs_tasks.py
> +    max_retry: int = 1,
max_retry -> max_retries

2022-03-04 23:40 UTC, felipaoo commented on fast_agave/tasks/sqs_tasks.py
> +                            message['Attributes']['ApproximateReceiveCount']
cuando el mensaje se lee por primera vez, que valor tiene `ApproximateReceiveCount`?

2022-03-05 00:17 UTC, andreshndz commented on fast_agave/tasks/sqs_tasks.py
> +                            message['Attributes']['ApproximateReceiveCount']
`'1'`

2022-03-05 00:27 UTC, andreshndz commented on fast_agave/tasks/sqs_tasks.py
> +        if last_retry:
Es que esta lógica no va a funcionar:

1- Si una tarea termina bien y de manera satisfactoria, no se va a borrar del SQS a menos que sea el `last_retry`. Esto haría que la tarea se ejecute tantas veces como `max_retries` diga
2- Si una tarea termina con `RetryTask`, se va a repetir infinitamente por el `return`

2022-03-05 00:28 UTC, andreshndz commented on fast_agave/tasks/sqs_tasks.py
> +    await sqs.delete_message(
Lee el comentario de abajo y ves mi explicación

2022-03-05 00:46 UTC, andreshndz commented on tests/tasks/test_sqs_tasks.py
> +
Ambos tests cubren distintas cosas, es mejor dejarlos

2022-03-05 02:44 UTC, andreshndz commented on tests/tasks/test_sqs_tasks.py
> +    assert 'Messages' not in resp
El tema es que con cualquier excepción, `Exception` por ejemplo, la corrutina no termina, arroja el error y deja el mensaje en la cola. No lo elimina

2022-03-07 22:30 UTC, felipaoo approved these changes
nomas falta cambiar la versión release

2022-03-07 23:59 UTC, merged