Adding request to update resource
cuenca-mx/fast-agave pull request #93
Opened 2022-04-08 17:23 UTC by alexviquez

Se agrega el request al cuerpo de el update, para el caso que se necesite extraer información del cliente

2022-04-08 17:58 UTC, felipaoo requested changes
ahh prrrro!

2022-04-08 17:58 UTC, felipaoo commented on requirements.txt
> +cuenca-validations==0.10.1.dev7
si vas a actualizar esta dependencia también deberías actualizar en el `setup.py`

2022-04-08 18:07 UTC, alexviquez commented
Solo falta `cuenca-validations` esperaré a que hagamos merge para poder mezclar ambos
https://github.com/cuenca-mx/cuenca-validations/pull/220

2022-04-11 16:36 UTC, felipaoo approved these changes

2022-04-11 16:38 UTC, merged